# Generated by Django 6.0.5 on 2026-07-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    """Backfill a Profile for any CustomUser created before this migration (e.g. the dev
    superuser auto-created by `runserver`, or existing rows in a pre-existing database)."""
    CustomUser = apps.get_model("users", "CustomUser")
    Profile = apps.get_model("users", "Profile")
    for user in CustomUser.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
